export const GET_CURRENT_INGRIDIENT_REQUEST = "GET_CURRENT_INGRIDIENT_REQUEST";
export const GET_CURRENT_INGRIDIENT_SUCCESS = "GET_CURRENT_INGRIDIENT_SUCCESS";
export const GET_CURRENT_INGRIDIENT_FAILED = "GET_CURRENT_INGRIDIENT_FAILED";
export const GET_CURRENT_INGRIDIENT_DELETE = "GET_CURRENT_INGRIDIENT_DELETE";